const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.NinePatch,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.layerscrollx,
		C3.Plugins.System.Exps.layerscrolly,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Touch.Cnds.OnTouchStart
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Fade: 0},
	{World: 0},
	{Touch: 0},
	{Audio: 0},
	{Background: 0},
	{Identification: 0},
	{Button: 0},
	{Mouse: 0},
	{CatBoundingBox: 0},
	{Array: 0},
	{PlatformInfo: 0},
	{Sine: 0},
	{Logo: 0},
	{Instructor: 0},
	{SpeechBalloon: 0},
	{Modal: 0},
	{Instructions: 0},
	{CatCounter: 0},
	{CatCounterBackground: 0},
	{ButtonIcon: 0},
	{Flash: 0},
	{Hint: 0},
	{PawnPattern: 0},
	{CanvasFrame: 0},
	{ReturnToMainMenu: 0},
	{Credits: 0},
	{OffsetDirection: 0},
	{ScrollingAngle: 0},
	{CatPattern: 0},
	{MainMenuCat: 0},
	{Noise: 0},
	{Confetti: 0},
	{Timer: 0},
	{CatBackgroundCircle: 0},
	{Cats: 0},
	{ColorMask: 0},
	{CatUID: 0},
	{SkipAnimation: 0},
	{FoundAnyErrors: 0},
	{TextIndex: 0},
	{DIALOGUETEXT: 0},
	{Text: 0},
	{BoopCooldown: 0},
	{TotalCatsFound: 0},
	{LAYOUTTRANSITIONDURATION: 0},
	{NextLayoutNameBuffer: 0},
	{IsBusy: 0},
	{NextLayoutName: 0},
	{InputFocus: 0},
	{Index: 0},
	{StartingWidth: 0},
	{StartingHeight: 0},
	{ReferenceX: 0},
	{ReferenceY: 0},
	{ChangeX: 0},
	{ChangeY: 0},
	{IgnoreCat: 0},
	{ReferenceDistance: 0},
	{Change: 0},
	{ButtonTiltDirection: 0},
	{ButtonUID: 0},
	{PositionX: 0},
	{PositionY: 0},
	{Delta: 0},
	{Scale: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{DEFAULTSFXVOLUME: 0},
	{DEFAULTBGMVOLUME: 0},
	{SFXVolume: 0},
	{BGMVolume: 0},
	{SFXName: 0},
	{IgnoreSFXVolume: 0},
	{BGMName: 0},
	{IgnoreBGMVolume: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0},
	{IsWithinRange: 0},
	{Minimum: 0},
	{Maximum: 0},
	{Target: 0},
	{FiniteLerpThreshold: 0},
	{InterpolatedValue: 0},
	{PointA: 0},
	{PointB: 0},
	{Factor: 0},
	{HasBooted: 0},
	{TextBuffer: 0}
];

self.InstanceType = {
	Fade: class extends self.ITiledBackgroundInstance {},
	World: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.IWorldInstance {},
	Mouse: class extends self.IInstance {},
	CatBoundingBox: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	Logo: class extends self.ISpriteInstance {},
	Instructor: class extends self.ISpriteInstance {},
	SpeechBalloon: class extends self.IWorldInstance {},
	Modal: class extends self.ITiledBackgroundInstance {},
	Instructions: class extends self.ITextInstance {},
	CatCounter: class extends self.ITextInstance {},
	CatCounterBackground: class extends self.ISpriteInstance {},
	ButtonIcon: class extends self.ISpriteInstance {},
	Hint: class extends self.ITextInstance {},
	PawnPattern: class extends self.ITiledBackgroundInstance {},
	CanvasFrame: class extends self.IWorldInstance {},
	Credits: class extends self.ITextInstance {},
	CatPattern: class extends self.ITiledBackgroundInstance {},
	MainMenuCat: class extends self.ISpriteInstance {},
	Noise: class extends self.ITiledBackgroundInstance {},
	Confetti: class extends self.IParticlesInstance {},
	CatBackgroundCircle: class extends self.ISpriteInstance {},
	Cats: class extends self.ISpriteInstance {},
	ColorMask: class extends self.ITiledBackgroundInstance {}
}